baseURL: "https://cookbook.deedoubledub.com/"
languageCode: "en-us"
title: "Cookbook"
theme: "cookbook"

menu:
  main:
  - name: "Home"
    pre: "book-open"
    url: "/"
    weight: 1
  - name: "Recipes"
    pre: "shopping-cart"
    url: "/recipes/"
    weight: 2
  - name: "Cocktails"
    pre: "coffee"
    url: "/cocktails/"
    weight: 3
  - name: "Tags"
    pre: "tag"
    url: "/tags/"
    weight: 4
